### PR TITLE
Fix #1177 - Added function-advanced snippet

### LINKED ISSUE #1177: snippet "Function advanced"
Can you add a snippet for an advanced function (just like in ISE) ?
thanks

### PR DESCRIPTION
**Pull request by Benny1007**
Added a function-advanced snippet based on the existing cmdlet snippet.

Leaves option to have more basic 'function' snippet based on the ISE 'function' snippet if required.

First PR, so grateful for further guidance.

### CODE REVIEW

**Comment by timoline** [comment]
only renaming cmdlet and ex-cmdlet would fix this thing, or am I wrong?

**Comment by rkeithhill** [comment]
This is practically identical to the existing `cmdlet` snippet.  A number of the existing snippet names (including cmdlet) where taken from the ISE snippets.

**Comment by tylerl0706** [comment]
Merged! Congrats on your 1st contribution @Benny1007!

**Comment by timoline** [comment]
https://github.com/Microsoft/vscode/issues/42838 is added,

snippits could ne merged now

**Comment by jcklpe** [comment]
Hey I see this has been merged etc. Is there a place in documentation that I can see the syntax for adding multiple prefixes to my snippets? 

Is it just `"prefix": ["console.log","print"]` ?

**Pull request merged**
