### PR TITLE
add script to generate changelog

### PR DESCRIPTION
**Pull request by tylerl0706**
In an attempt to automate more of the release process, here's a script to autogenerate the changelog listing all the commits and if they're from external contributors.

Here's what it outputs:

```
## v1.8.0
### Monday, June 25, 2018
#### [vscode-powershell](https://github.com/powershell/vscode-powershell)

- have PSES generate the random pipename
- revert transport type
- allow path to named pipes to be passed down
- Update to TypeScript 2.9.x (#1344) (Thanks @rkeithhill!)
- SpecProcId - interactive var replacement supports only string type (#1323) (Thanks @rkeithhill!)
- Switch to named pipes (#1327)
- GitHub issue template tweaks and add PSSA template (#1321) (Thanks @bergmeister!)
- Take advantage of multiple issue templatesShamelessly ripping this off from the PSSA GH repo (#1320) (Thanks @rkeithhill!)
- Change SpecifyScriptArgs command to only return string - not string[] (#1317) (Thanks @rkeithhill!)
- Update package veresion in lock file, format package.json file. (#1318) (Thanks @rkeithhill!)
- Updates to Examples PSSA settings file to include more rule config (#1312) (Thanks @rkeithhill!)
- Make SaveAs work for untitled files (#1305)
- Added Columns, Improved readability for ToC. (#1307) (Thanks @st0le!)
- Added some snippets (#1297) (Thanks @SQLDBAWithABeard!)

#### [PowerShellEditorServices](https://github.com/powershell/PowerShellEditorServices)

- add what to do when there's a vulnerability to docs (#687)
- Fix issue where MS Dynamics CRM (#686) (Thanks @rkeithhill!)
- Make AnalysisService use the latest version of PSScriptAnalyzer (#677)
- Fix PSES crash that happens if you format an empty PS doc (#685) (Thanks @rkeithhill!)
- Include ThirdPartyNotices.txt to comply with OSS guidelines
- Initial CODEOWNERS file to auto assign PR reviewers (#681) (Thanks @rkeithhill!)
- Add more useful PSSA rules that should be enabled by default (#669) (Thanks @bergmeister!)
- Add symbols to modules built in Debug configuration (#675)
- Implement initialized notification handler to get rid of log error (#674) (Thanks @rkeithhill!)
- Change logging to use Serilog (#666)
- Stop before we restart (#668)
- Add .gitattributes, .editorconfig and extensions.json (#667) (Thanks @rkeithhill!)
- ignore .idea folder that jetbrains products like to spit out (Rider, IntelliJ, Resharper) (#664)
- Close stray processes on exit (#663)
```

### CODE REVIEW

**Comment by rjmholt** [comment]
Wow! This is awesome!

**Comment by tylerl0706** [comment]
tbh, stole most from the PowerShell repo :) 

https://github.com/PowerShell/PowerShell/blob/master/tools/releaseTools.psm1#L129

**Comment by rjmholt** [comment]
We should probably document any of the bits we need to make this work somewhere in the repo (like in the README). The big one I'm thinking of is `[Breaking Change]`.

**Comment by rjmholt** [comment]
But also just making sure the final, post-squash commit message looks right in the changelog

**Pull request merged**
