### PR TITLE
Replace issue templates with modern issue forms

### PR DESCRIPTION
**Pull request by andschwa**
We should do this for PRs too, and update the "Upload Bug Report to GitHub" command.

### CODE REVIEW

**Comment by andschwa** [comment]
Tried testing this in my fork but the forms don't seem enabled. We may have to ask GitHub to enable this "beta" feature for us.

**Comment by andschwa** [comment]
Similar to https://github.com/DV8FromTheWorld/JDA/pull/1546 we'll just leave this as a draft until Issue Forms enter *public* beta (or I ask a support engineer to add us to the closed beta).

**Comment by andschwa** [comment]
I've pinged my support ticket with GitHub every couple days but haven't received a single response (not even a "no") since I opened it 18 days ago. 😢

**Comment by andschwa** [comment]
Yay! I found a forum and they've followed up with me! Apparently the ticket was responded to but that was never sent, and then it fell through the cracks. Hey, it happens! Just submitted a request through the right channel to get us opted into the beta. 🥳

**Comment by andschwa** [comment]
@rjmholt I think this is ready to go except for that the placeholders munge newlines. I've reported the bug back to GitHub support (and it's affecting other repos too). Go to the files in the PR and click "view" to see the template preview.

**Review by rjmholt — APPROVED** [review]

**Pull request merged**
