### PR TITLE
Update VS Code engine to 1.79.0

### PR DESCRIPTION
**Pull request by andschwa**
Now that Azure Data Studio is doing the same in:
https://github.com/microsoft/azuredatastudio/pull/23482

### CODE REVIEW

**Comment by andschwa** [comment]
@JustinGrote this will unblock https://github.com/PowerShell/vscode-powershell/issues/4441 and https://github.com/PowerShell/vscode-powershell/issues/4522!

**Comment by andschwa** [comment]
FWIW I don't think this is jumping the gun to merge today as they are clearly updating and we still need to put this through preview and into stable.

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

**Comment by JustinGrote** [comment]
Huzzah! We'll give this a bit to make sure there's no regressions and maybe I'll get started on the updated logger.

**Pull request merged**
