### PR TITLE
Session menu fails to open when PowerShell extension is starting

### PR DESCRIPTION
**Pull request by jeffpatton1971**
## PR Summary

This is the solution proposed by @GaelGirodon in Issue #2906 

There were no issues during the build and testing of this change, and the proper version of powershell was loaded and displayed in the task bar.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] PR has tests
- [ ] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
test failures are likely not your fault. I'll look into those

**Comment by jeffpatton1971** [comment]
Thanks @TylerLeonhardt like I said it built out fine locally :)

**Comment by jeffpatton1971** [comment]
OH I also I chose master, because I didn't really know what branch to use, wasn't really sure how to progress from there.

**Comment by TylerLeonhardt** [comment]
master is correct.

**Review by rjmholt — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
Given the low risk of this change, and the test failures are happening in master already... I'll merge this in

**Review by TylerLeonhardt — APPROVED** [review]

**Pull request merged**
