### PR TITLE
Update package-lock.json for 2020.7.0

### PR DESCRIPTION
**Pull request by rjmholt**
## PR Summary

Based on https://github.com/PowerShell/vscode-powershell/pull/2828, but I ran the build to update the `package-lock.json` as well as `npm audit fix`.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by bergmeister** [comment]
Happy to take that PR alternatively as well, I didn't know about the audit option of npm

**Comment by rjmholt** [comment]
> I didn't know about the audit option of npm

It just told me when I ran a clean build -- seemed like a good idea

**Comment by rjmholt** [comment]
Closing in favour of #2828

**Comment by bergmeister** [comment]
> Closing in favour of #2828

Why? My PR does not contain the audit fixes. Ideally my PR should be just the version fix and yours the audit fix.

**Comment by rjmholt** [comment]
> Why? My PR does not contain the audit fixes. Ideally my PR should be just the version fix and yours the audit fix.

I've added the audit fixes to your PR

**Pull request closed without merging**
