### PR TITLE
Per VSCode team request, move vscode to devDependencies

### LINKED ISSUE #1604: Please do not use `vscode` in the `dependencies` section of `package.json`
The `vscode` npm module contains some helper stuff which can download vscode for testing purposes if you use continuous integration, which can download the `vscode.d.ts`, but which also drags in a lot of dependencies. The `engines` field is the place which captures that this is a vscode extension and it is enforced at runtime.

Using `vscode` in the `dependencies` section leads to a lot larger extension size (for no good reason).

The correct place to put it is in `devDependencies`.

### PR DESCRIPTION
**Pull request by rkeithhill**
Closes #1604

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by rkeithhill** [comment]
@TylerLeonhardt @rjmholt  What do you think about this one?  Merge it?

**Comment by rkeithhill** [comment]
Hmm, `npm install --production` fails.  Not a great sign but wouldn't the builds catch such a problem?

**Comment by TylerLeonhardt** [comment]
Looks like we run regular `npm install` which means devDependencies have been shipping with the extension for probably ever. 😥

https://github.com/PowerShell/vscode-powershell/blob/master/vscode-powershell.build.ps1#L69

**Comment by alexandrudima** [comment]
@TylerLeonhardt If you are publishing using `vsce`, that is smart enough to only package production dependencies.

**Comment by TylerLeonhardt** [comment]
Good to know! In that case, @rkeithhill can you test the VSIX that CI generated to make sure it still works?

**Comment by rkeithhill** [comment]
Yes, I'll test it tonight.

**Comment by rkeithhill** [comment]
Um yeah … wow!  AFAICT with some basic smoke testing (code analysis & debugging) the extension works and this change takes us from an installed size of 62.1 MB to 12.9 MB.  And the VSIX size goes from 7 MB to 3.5 MB.  

@alexandrudima good call.  Thanks!

**Comment by TylerLeonhardt** [comment]
That's amazing!!

**Pull request merged**
