### PR TITLE
Add quickfix functionality

### PR DESCRIPTION
**Pull request by kapilmb**

### CODE REVIEW

**Comment by daviwil** [comment]
Nice!  I'll hold on this for a bit because I'll need to fix up the code slightly due to some refactoring I'm finishing up now.

**Comment by kapilmb** [comment]
@daviwil  do you want me to rebase the changes over the refactored changes?

**Comment by kapilmb** [comment]
@daviwil rebased on recent changes to master.

**Comment by daviwil** [comment]
Thanks a lot for rebasing this on the new extension design.  Looks great!

**Pull request merged**
