### PR TITLE
Use spaces instead of tabs

### PR DESCRIPTION
**Pull request by xtqqczze**
* Use 4 spaces instead of tabs in general
* Use 2 space tabs for `*.{json,yaml,yml}` (match [microsoft/vscode](https://github.com/microsoft/vscode), [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell))
* Specify indent size and style in EditorConfig

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
please revert vscode.proposed.d.ts . That must have tabs because that file is kept up to date with a file in the vscode repo which uses tabs

**Comment by corbob** [comment]
Would it be an idea to add editorconfig to the recommended extensions? 

Alternatively: should the settings being put in editorconfig just be put in the vscode workspace settings? PSES uses editorconfig presumably because you could use any editor with it, but is it safe to assume anyone editing this project is using vscode?

**Comment by rjmholt** [comment]
Seems like if it works just as well in `.editorconfig`, it's best to put in there

**Comment by TylerLeonhardt** [comment]
Thanks!

**Comment by xtqqczze** [comment]
@corbob thanks for the suggestion, see #2922

**Pull request merged**
