### PR TITLE
Add key binding for Show Additional Commands

### LINKED ISSUE #196: Add a hotkey for PowerShell.ShowAdditionalCommands
It'd be useful to have a hotkey for the "PowerShell: Show additional commands from PowerShell modules" command which is the entry point for the editor command menu.

**FEEDBACK NEEDED:**  Any suggestions for a good hotkey?

/cc @gerane

### PR DESCRIPTION
**Pull request by dsolodow**
Adds default keyboard shortcut Ctrl-Alt-A for "Show Additional Commands from Modules".
Resolves #196

### CODE REVIEW

**Comment by tylerl0706** [comment]
I think we're not supposed to be using `Ctrl+Alt` key combinations in VS Code since they can conflict with Windows shortcuts.

Do you see any kind of errors in the Developer Tools console (Ctrl+Shift+I, check the Console tab) complaining about this shortcut?

I believe any other modifier combination is ok: `Ctrl-Shift`,  `Alt+Shift`. It's easy to test at least.

**Comment by dsolodow** [comment]
Modified PR with new binding to avoid Ctrl-Alt

**Comment by tylerl0706** [comment]
Thanks for this, @dsolodow!!

**Comment by rjmholt** [comment]
Just to document: the final keybinding here was <kbd>Shift</kbd>-<kbd>Alt</kbd>-<kbd>S</kbd>.

**Pull request merged**
