### PR TITLE
Update `vscode-languageclient` and refactor (a lot of TLC)

### LINKED ISSUE #4128: Language client failed to start in newest preview in Windows PowerShell 5.1
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

My extension autoupdated this morning and I got a message that language client failed to start. Works fine in 7.3 preview and 7.2 PowerShell. 

```
8:01:45 AM [NORMAL] - PowerShell Preview Extension v2022.8.1
8/12/2022 8:01:45 AM [NORMAL] - Operating System: Windows 64-bit
8/12/2022 8:01:46 AM [NORMAL] - Language server starting --
8/12/2022 8:01:46 AM [NORMAL] -     PowerShell executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
8/12/2022 8:01:46 AM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.8.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1660284105-52644f21-572b-410d-ae59-c73828b605e21660284103192\EditorServices.log' -SessionDetailsPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-7708-841903.json' -FeatureFlags @() 
8/12/2022 8:01:46 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.8.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1660284105-52644f21-572b-410d-ae59-c73828b605e21660284103192\EditorServices.log' -SessionDetailsPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-7708-841903.json' -FeatureFlags @() 
8/12/2022 8:01:46 AM [NORMAL] - powershell.exe started.
8/12/2022 8:01:46 AM [NORMAL] - Waiting for session file
8/12/2022 8:01:49 AM [NORMAL] - Session file found
8/12/2022 8:01:49 AM [NORMAL] - Registering terminal close callback
8/12/2022 8:01:49 AM [NORMAL] - Registering terminal PID log callback
8/12/2022 8:01:49 AM [NORMAL] - powershell.exe PID: 14212
8/12/2022 8:01:49 AM [NORMAL] - Language server started.
8/12/2022 8:01:49 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_e0prfkrz.qg5","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_a3vjb40l.omi"}
8/12/2022 8:01:49 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_e0prfkrz.qg5...
8/12/2022 8:01:49 AM [NORMAL] - Language service connected.
8/12/2022 8:01:51 AM [NORMAL] - Language client failed to start.
8/12/2022 8:01:51 AM [ERROR] - Language client failed to start: 
8/12/2022 8:01:51 AM [ERROR] - TypeError: Invalid Version: null
8/12/2022 8:02:02 AM [NORMAL] - Shutting down language client...
8/12/2022 8:02:02 AM [NORMAL] - Language server starting --
8/12/2022 8:02:02 AM [NORMAL] -     PowerShell executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
8/12/2022 8:02:02 AM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.8.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1660284122-52644f21-572b-410d-ae59-c73828b605e21660284103192\EditorServices.log' -SessionDetailsPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-7708-790005.json' -FeatureFlags @() 
8/12/2022 8:02:02 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.8.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\przemyslaw.klys\.vscode\extensions\ms-vscode.powershell-preview-2022.8.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1660284122-52644f21-572b-410d-ae59-c73828b605e21660284103192\EditorServices.log' -SessionDetailsPath 'c:\Users\przemyslaw.klys\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-7708-790005.json' -FeatureFlags @() 
8/12/2022 8:02:02 AM [NORMAL] - powershell.exe started.
8/12/2022 8:02:02 AM [NORMAL] - Waiting for session file
8/12/2022 8:02:04 AM [NORMAL] - Session file found
8/12/2022 8:02:04 AM [NORMAL] - Registering terminal close callback
8/12/2022 8:02:04 AM [NORMAL] - Registering terminal PID log callback
8/12/2022 8:02:04 AM [NORMAL] - powershell.exe PID: 35288
8/12/2022 8:02:04 AM [NORMAL] - Language server started.
8/12/2022 8:02:04 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_d3r5gxb4.dgt","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_b4ziz5df.iad"}
8/12/2022 8:02:04 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_d3r5gxb4.dgt...
8/12/2022 8:02:04 AM [NORMAL] - Language service connected.
8/12/2022 8:02:06 AM [NORMAL] - Language client failed to start.
8/12/2022 8:02:06 AM [ERROR] - Language client failed to start: 
8/12/2022 8:02:06 AM [ERROR] - TypeError: Invalid Version: null
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.832
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.832
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.70.1
6d9b74a70ca9c7733b29f0456fd8195364076dda
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.7.2
ms-vscode.powershell-preview@2022.8.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.6
```

### Steps to Reproduce

Updated extension to newest version

### Visuals

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by andschwa**
Hopefully fixes #4128 by eliminating race conditions in the `LanguageClient`'s connection process.

### CODE REVIEW

**Review by SeeminglyScience — APPROVED** [review]
LGTM! well done 🎉 

(after tests pass ofc)

**Comment by andschwa** [comment]
FYI @Charles-Gagnon we had to bump our engine to 1.65 in order to (finally) take the language client library update. What's ADS's ETA to merge 1.65?

**Comment by Charles-Gagnon** [comment]
No exact ETA at this point in time - we're working on another update currently though (probably for October/November) that may get up that far, if not then it'll be sometime early next year.

**Comment by andschwa** [comment]
No worries, if you need we can back-port some patches and cut you a new release, but hopefully you can just take this one sooner rather than later!

**Pull request merged**
