### PR TITLE
Change Whitespace settings to camelCase

### PR DESCRIPTION
**Pull request by rjmholt**

### CODE REVIEW

**Comment by rjmholt** [comment]
I've been trying to test this and the settings don't do anything. They also don't do anything in our current release. I've verified in the debugger that we send the right settings through, and also verified that the problem doesn't occur with `Invoke-Formatter` by itself. Running out of ideas here.

**Comment by rkeithhill** [comment]
Any chance you could have an earlier version of PSSA loaded?  `(Get-Runspace 4).CreatePipeline("gmo", 0).Invoke()`

**Comment by rjmholt** [comment]
```
PS C:\Users\roholt\Documents\Dev\PowerShell> (Get-Runspace 4).CreatePipeline("gmo", 0).Invoke()


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Script     1.18.0     PSScriptAnalyzer                    {Get-ScriptAnalyzerRule, Invoke-Formatter, Invoke-ScriptAnalyzer}

```

**Comment by rkeithhill** [comment]
Hmm, nope, that's not the problem.

**Comment by bergmeister** [comment]
- `powershell.codeFormatting.WhitespaceAroundPipe` makes `if ($true) {foo}` change to `if ($true) { foo }` if the setting is enabled
- `powershell.codeFormatting.WhitespaceInsideBrace` makes `foo|bar` change to `foo | bar` if the setting is enabled
I have verified the setting can be turned on and off and works fine. Since I am a developer, I even installed the latest official releases versions of PowerShell 6.2.0, PSSA 1.18.0, code-insiders and v 1.12 of the code extension. I am on Windows 10 Pro 1809

**Comment by rjmholt** [comment]
@bergmeister 

Script is:

```powershell
gmo|
    ? {$_.IsDuck }|
    git
```

Settings include:
```json
"powershell.codeFormatting.whitespaceAroundPipe": true,
```

At that point <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> does nothing in the program.

However, I've just realised while looking at it that this might be a problem in the client. I'm seeing this error when I send that key chord:

```
[ms-vscode.powershell] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'editor.insertSpaces', provide the URI of a resource or 'null' for any resource.
```

Going to look into that now

**Comment by bergmeister** [comment]
Ok, interesting. I use `Ctrl`+`K`+`F` to format.

**Comment by rjmholt** [comment]
Fixing that warning didn't help

**Comment by bergmeister** [comment]
Hmm, are you on Windows as well and do the examples that I provided work for you. I will try your examples later.

**Comment by rjmholt** [comment]
```
> $PSVersionTable                                                                                                            
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18875
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Examples you gave aren't working either unfortunately.

I'm stepping through in the debugger and have the following:

dbgView1
dbgView2

So as far as I can tell it's calling `Invoke-Formatter` with the right values. Equivalent to:

```powershell
Invoke-Formatter -Settings @{
    Rules = @{
        PSPlaceCloseBrace = @{ NewLineAfter = $false; IgnoreOneLineBlock = $true; Enable = $true }
        PSUseConsistentWhitespace = @{
            Enable = $true
            CheckInnerBrace = $true
            CheckOperator = $true
            CheckPipe = $true
            CheckOpenParen = $true
            CheckSeparator = $true
            CheckOpenBrace = $true
        }
        PSAlignAssignmentStatement = @{ CheckHashtable = $true; Enable = $true }
        PSUseCorrectCasing = @{ Enable = $false }
        PSPlaceOpenBrace = @{
            NewLineAfter = $true
            IgnoreOneLineBlock = $true
            Enable = $true
            OnSameLine = $true
        }
        PSUseConsistentIndentation = @{
            Enable = $true
            PiplineIndentation = $true
            Kind = 'space'
            IndentationSize = 4
        }
    }
    IncludeRules = @(
        'PSPlaceCloseBrace'
        'PSPlaceOpenBrace'
        'PSUseConsistentWhitespace'
        'PSUseConsistentIndentation'
        'PSAlignAssignmentStatement'
    )
} -ScriptDefinition @'
if ($true) {foo}

foo|bar
'@ 
```

Running that on my machine in the console gives me:

```
if ($true) {foo}

foo|bar
```

I also get that result inside PSES and then that gets returned. So it looks like it's the `Invoke-Formatter` call where the problem is occurring here.

**Comment by rjmholt** [comment]
```
> $PSVersionTable                                                                                                            
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18875
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Examples you gave aren't working either unfortunately.

I'm stepping through in the debugger and have the following:

dbgView1
dbgView2

So as far as I can tell it's calling `Invoke-Formatter` with the right values. Equivalent to:

```powershell
Invoke-Formatter -Settings @{
    Rules = @{
        PSPlaceCloseBrace = @{ NewLineAfter = $false; IgnoreOneLineBlock = $true; Enable = $true }
        PSUseConsistentWhitespace = @{
            Enable = $true
            CheckInnerBrace = $true
            CheckOperator = $true
            CheckPipe = $true
            CheckOpenParen = $true
            CheckSeparator = $true
            CheckOpenBrace = $true
        }
        PSAlignAssignmentStatement = @{ CheckHashtable = $true; Enable = $true }
        PSUseCorrectCasing = @{ Enable = $false }
        PSPlaceOpenBrace = @{
            NewLineAfter = $true
            IgnoreOneLineBlock = $true
            Enable = $true
            OnSameLine = $true
        }
        PSUseConsistentIndentation = @{
            Enable = $true
            PiplineIndentation = $true
            Kind = 'space'
            IndentationSize = 4
        }
    }
    IncludeRules = @(
        'PSPlaceCloseBrace'
        'PSPlaceOpenBrace'
        'PSUseConsistentWhitespace'
        'PSUseConsistentIndentation'
        'PSAlignAssignmentStatement'
    )
} -ScriptDefinition @'
if ($true) {foo}

foo|bar
'@ 
```

Running that on my machine in the console gives me:

```
if ($true) {foo}

foo|bar
```

I also get that result inside PSES and then that gets returned. So it looks like it's the `Invoke-Formatter` call where the problem is occurring here.

**Comment by rjmholt** [comment]
Here is the verbose output:

```
VERBOSE: Running PSUseConsistentWhitespace rule.
VERBOSE: Found 0 violations.
VERBOSE: Fixed 0 violations.
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Analyzing Script Definition.
```

**Comment by rjmholt** [comment]
More data:

```
> Invoke-Formatter -Settings @{
>>     Rules = @{
>>         PSUseConsistentWhitespace = @{
>>             Enable = $true
>>             CheckInnerBrace = $true
>>             CheckOperator = $true
>>             CheckPipe = $true
>>             CheckOpenParen = $true
>>             CheckSeparator = $true
>>             CheckOpenBrace = $true
>>         }
>>     }
>>     IncludeRules = @(
>>         'PSUseConsistentWhitespace'
>>     )
>> } -ScriptDefinition @'
>> if ($true) {foo}
>>
>> foo|bar
>> '@  -Verbose
VERBOSE: Using settings hashtable.
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.PowerShell.CrossCompatibility.dll
VERBOSE: Loading Assembly:Microsoft.PowerShell.CrossCompatibility
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules
VERBOSE: Found Assembly: C:\Users\roholt\Documents\PowerShell\Modules\PSScriptAnalyzer\coreclr\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
VERBOSE: Loading Assembly:Microsoft.Windows.PowerShell.ScriptAnalyzer
VERBOSE: Analyzing Script Definition.
VERBOSE: Running PSUseConsistentWhitespace rule.
VERBOSE: Found 0 violations.
VERBOSE: Fixed 0 violations.
if ($true) {foo}

foo|bar
```

**Comment by rjmholt** [comment]
Ok I've just reinstalled PSScriptAnalyzer and it's working now. I suspect I somehow had a bad build.

**Comment by rjmholt** [comment]
Sorry about all that @bergmeister! :)

**Comment by bergmeister** [comment]
No worries, I created an issue in PSSA to capture your special case whereby together with the set of settings, the  formatting does not work exactly as expected

**Pull request merged**
