### PR TITLE
Use property scope in ISE theme

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
## PR Summary

Goes with https://github.com/PowerShell/PowerShellEditorServices/pull/1337

image
before and after

ISE:
image

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests N/A
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@justinytchen what do you think?

**Comment by TylerLeonhardt** [comment]
This change was due to @PrzemyslawKlys tweet about the Monokai theme:
https://twitter.com/PrzemyslawKlys/status/1288961019373649920?s=20

**Comment by PrzemyslawKlys** [comment]
Does this mean my issue will be gone (as in reverted for non ISE theme) or that I will be able to control those colors or better that those colors would be taken from the theme natively? 

It does seem to give some benefits I guess - just the colors are not really something I would like to keep :-)

image

image
 
image

**Comment by PrzemyslawKlys** [comment]
Never mind, I see the other issue that demonstrates it. Thank you!

**Pull request merged**
