### PR TITLE
Change "Open In ISE" shortcut

### PR DESCRIPTION
**Pull request by tylerl0706**
This changes the "Open In ISE" shortcut to `ctrl+alt+i` to address #1115.

### CODE REVIEW

**Comment by tylerl0706** [comment]
@rkeithhill it's the sig change from the 1.5.1 release. I just never updated the repo with it.

**Comment by daviwil** [comment]
I think we're not supposed to be using `Ctrl+Alt` key combinations in VS Code since they can conflict with Windows shortcuts.  Do you see any kind of errors in the Developer Tools console (Ctrl+Shift+I, check the Console tab) complaining about this shortcut?

**Comment by tylerl0706** [comment]
@daviwil I changed it to `shift+alt+p`

**Comment by tylerl0706** [comment]
Does that sound good to everyone

**Comment by SeeminglyScience** [comment]
Not sure how big of a deal it is, but it does conflict with a popular extension [Project Manager](https://github.com/alefragnani/vscode-project-manager).  I wish we had some data on how often this is used.  Having a default key bind for this when the extension was really early made sense, but I wonder if it's really needed these days.

**Comment by tylerl0706** [comment]
@SeeminglyScience we _could_ remove the functionality until someone complains :)

**Comment by SeeminglyScience** [comment]
@tylerl0706 I'm more suggesting the default key bind be removed until someone complains.  The functionality would still available from the command palette.  Though I suspect the folks still using the ISE may not be super used to the command palette.

**Comment by daviwil** [comment]
Actually, Patrick's suggestion makes sense to me.  My feeling is that this keybinding isn't relevant for 90% of the PS extension users so we could safely remove it.  If someone wants to bind this command to a key combo, they can do so very easily.

**Comment by tylerl0706** [comment]
We were saying the same thing, I was just too vague :)

**Comment by rkeithhill** [comment]
Agreed.  And if folks want to, they can bind the command to a shortcut of their choice.  Then they can avoid stomping editor shortcuts they use.

**Comment by tylerl0706** [comment]
Alright, I've removed the keybinding but you can still "Open in ISE" using the command pallet if you so choose.

**Pull request merged**
