### PR TITLE
Fix: Change DAP send/receive glyph to keep things aligned in the logs

### PR DESCRIPTION
**Pull request by JustinGrote**
## PR Summary

Changes logging glyph from ◀️ to ⬅️ which has better ZWF formatting in logs

### CODE REVIEW

**Review by andyleejordan — APPROVED** [review]

**Comment by andyleejordan** [comment]
@JustinGrote are you sure you have the right right-arrow? I'd expect to see ➡️ since I'm seeing ⬅️ but I'm seeing ➡️...which I just copy-pasted and it shows correctly here. GitHub isn't rendering it well in the file diff 😭

**Comment by andyleejordan** [comment]
Screenshot 2024-10-31 at 10 18 46 AM

**Comment by JustinGrote** [comment]
Looks fine to me in Github...
image

And in Code:
image

**Comment by JustinGrote** [comment]
Files changed tab looks fine to me too in github on the PR:
image

Are you on a Mac or something? Also using edge browser here.

**Comment by JustinGrote** [comment]
Checking the glyph codepoints they look good to me, so I'm going to go ahead and merge queue it. If we find something's wrong with the code points we can fix-forward, but again since this is just the DAP trace log and not user-facing it's not a big deal either way.

**Comment by andyleejordan** [comment]
> Files changed tab looks fine to me too in github on the PR: image
> 
> Are you on a Mac or something? Also using edge browser here.

Yeah, in Edge on a Mac. It's weird! No worries though.

**Pull request merged**
