### PR TITLE
Add new integrated console settings

### PR DESCRIPTION
**Pull request by daviwil**
See commits for more information.

### CODE REVIEW

**Comment by daviwil** [comment]
@rkeithhill What do you think about the name of the `powershell.startAutomatically` setting?  Any better ideas?

**Comment by rkeithhill** [comment]
So this really is whether to actually start PSES?  Is there no way to start the extension but not automatically show the IC?

**Comment by daviwil** [comment]
@rkeithhill There are two separate settings here, one is to automatically start PSES and the other is to automatically show the console when PSES starts.  In the original issue that was filed, the author asked if we could add a setting to defer starting PSES until later.

**Comment by rkeithhill** [comment]
Not starting PSES seems a bit strange given it occurs in the background (spinning up a different process).  I wouldn't think it would impact editing performance that much.  The name seems reasonable to me.  

I wonder how long it will be before we get an issue that the extension isn't working because someone set this setting to true?  😛

**Comment by daviwil** [comment]
Starting up PSES does have some impact on slower machines just due to another process loading and taking up CPU cycles, but I suppose it isn't happening in the foreground so it isn't blocking the user from using the editor.  I'll leave the setting in for now even though there's a risk of someone shooting off their foot ;)

**Pull request merged**
