### PR TITLE
(maint) Add visual ruler for line length

### PR DESCRIPTION
**Pull request by glennsarti**
## PR Summary

Previously it was a little difficult to know when your editing would exceed
the 120 line length limit.  This commit modifies the project settings to add
a simple visual ruler at the 120 char limit.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by glennsarti** [comment]
Hrmm odd.  Appveyor ignored my `[skip ci]`

**Comment by rkeithhill** [comment]
Oh, one minor nit, would you mind moving this setting up by the other `editor` settings?

**Comment by rkeithhill** [comment]
Yes, please move it up to line 5 and then I'll merge this PR.  Thanks!

**Comment by glennsarti** [comment]
Done.  Also added an EOF line feed as it was missing.

**Comment by rjmholt** [comment]
Sorry I meant I'm in favour of @rkeithhill's proposed changes

**Comment by rkeithhill** [comment]
Thanks!

**Pull request merged**
