### PR TITLE
Modernize built-in snippets

### PR DESCRIPTION
**Pull request by JustinGrote**
Evaluate and modernize existing snippets. This will be a breaking change in some cases, we should provide guidance for restoring existing snippets for any cranky people :).

After this  PR, snippets may be further improved by moving them out of JSON definition and into typescript, the primary improvement being that we can define the description with a MarkdownString and include help links, etc. but how much of that should just be returned by the LSP vs. a snippet is TBD.

- [ ] ~~ArgumentCompleterAttribute ScriptBlock~~ - Redundant and not useful since you cant use a variable with an ArgumentCompleter
- [x] ArgumentCompleterAttribute ~~with ScriptBlock~~ - Renamed and more descriptive help added. Added final tabstop after argumentcompleter
- [x] CalculatedProperty - description and  help reference
- [x] Class - description and help reference
- [x] comment block
- [ ] ~~Comment-Help~~ Replaced with `Function Help`
- [x] Constructor - description and help reference
- [x] do-until - description and help reference
- [x] do-while - description and help reference
---
## Should DSC move to community snippets?
- [ ] DSC Ensure Enum
- [ ] DSC Resource Provider (class-based)
- [ ] DSC Resource Provider (function-based)
---
- [x] else - description and help reference
- [x] elseif  - description and help reference
- [x] Enum - description and help reference
- [ ] ~~Example-Advanced Workflow~~ - Workflows are deprecated, we should encourage parallel instead.
---
## Should we still have examples or should the examples be with placeholders?
- [ ] Example-Class
- [ ] Example-Cmdlet
- [ ] Example-DSC Configuration
- [ ] Example-DSC Resource Provider (class-based)
- [ ] Example-DSC Resource Provider (function based)
- [ ] Example-Path Processing for No Wildcards Allowed
- [ ] Example-Path Processing for Non-Existing Paths
- [ ] Example-Path Processing for Wildcards Allowed
- [ ] Example-Splatting
- [ ] Example-Switch
---

- [x] for - description and help reference,
- [ ] for-reversed
- [x] foreach
- [x] function
- [x] Function-Advanced- description and help reference, update aliases
- [x] Function-Help- description and help reference, update aliases
- [x] Function-Inline- description and help reference, update aliases
- [x] Hashtable- description and help reference, update aliases
- [x] Hidden Property- description and help reference, update aliases
- [x] IArgumentCompleter Class - description and help reference, update aliases
- [x] if - description and help reference,
- [x] IfShouldProcess  - description and help reference, update aliases
- [ ] Method
- [ ] ModuleManifest
- [x] Parameter  - description and help reference, update aliases
- [x] Parameter_Block  - description and help reference, update aliases
- [x] Parameter-LiteralPath  - description and help reference, update aliases
- [x] Parameter-Path  - description and help reference, update aliases
- [x] Parameter-Path-Wildcards  - description and help reference, update aliases
---
## Should Pester Move to Community Snippets since it is no longer bundled with Powershell?
- [ ] PesterContext
- [ ] PesterContextIt
- [ ] PesterDescribeBlock
- [ ] PesterDescribeContextIt
- [ ] PesterIt
---

- [ ] Property
- [ ] PSCustomObject
- [ ] Region Block
---
## Intellisense now handles the requires, there was a comment that these should be removed when it does.
- [ ] ~~Requires Assembly~~
- [ ] ~~Requires Assembly Path~~
- [ ] ~~Requires Assembly Version~~
- [ ] ~~Requires Module~~
- [ ] ~~Requires Module RequiredVersion~~
- [ ] ~~Requires Module Version~~
- [ ] ~~Requires PSEdition~~
- [ ] ~~Requires PSSnapin~~
- [ ] ~~Requires PSSnapin Version~~
- [ ] ~~Requires RunAsAdministrator~~
- [ ] ~~Requires ShellId~~
- [ ] ~~Requires Version~~
---
- [x] Suppress PSScriptAnalyzer Rule - rewritten to multiline, description, and help reference
- [x] Suppress PSScriptAnalyzer Rule in Scope - rewritten to multiline, description, and help reference
- [x] Suppress PSScriptAnalyzer Rule on Parameter - rewritten to multiline, description, and help reference
- [x] switch  - description and help reference
- [x] try-catch - description and help reference
- [x] try-catch-finally - description and help reference
- [x] try-finally - description and help reference
- [x] while - description and help reference
---
## Workflows are deprecated and not supported in 6+, we should not be encouraging their use.
- [ ] ~~Workflow~~ 
- [ ] ~~Workflow ForEachParallel~~
- [ ] ~~Workflow InlineScript~~
- [ ] ~~Workflow Parallel~~
- [ ] ~~Workflow Sequence~~
---
# NEW
* Function Help - Better Comment based help with tabstopes
* Pipeline Function - A simple definition of a function that is pipelineable
* Parallel Pipeline Function - A simple definition of a function that uses foreach-parallel to process items in the pipeline in parallel.
* Ternary - build a ternary condition
* Splat - Select a function name and it will build a splat for it. This is *not* a refactor for an existing function.
* Here String
* Literal Here String

### CODE REVIEW

**Comment by JustinGrote** [comment]
@andschwa first pass done. There's a lot of things here that I think are more community questions: Should we retain legacy snippets for deprecated and discouraged features like workflows, should we retain pester now that it's no longer bundled with PS, etc.

**Comment by JustinGrote** [comment]
@andschwa Build failure is not me:
```
ERROR: The script 'PowerShellEditorServices.build.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: platyPS.
```

**Comment by andschwa** [comment]
> @andschwa Build failure is not me:
> 
> ```
> ERROR: The script 'PowerShellEditorServices.build.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: platyPS.
> ```

Fixed it! Sorry about that. 😅 Give it a rebase and it should work. This is looking great!

**Comment by andschwa** [comment]
I rebased it!

**Comment by JustinGrote** [comment]
Should be good to go. A lot of these snippets support the vscode "snippet in place" method now. For example, type `Invoke-Restmethod`, highlight it, and then overwrite it with `splat` and hit tab or select the completion snippet.

**Comment by andschwa** [comment]
@JustinGrote do you know what this issue means: https://github.com/PowerShell/vscode-powershell/issues/3404 ? 😂

**Comment by JustinGrote** [comment]
@andschwa it's a symptom of an issue closed for workaround that we may want to reopen
https://github.com/PowerShell/vscode-powershell/issues/3456

**Comment by JustinGrote** [comment]
Disregard, I was mistaken, this is part of the snippet itself. It can be configured either way, but we should decide if we are going to change the consensus on whether $ is considered a word separator or not (e.g. double clicking $this if it highlights the whole thing or just "this"), whatever that decision, the snippets can follow suit. As of today I have them matching the existing behavior ($ is excluded), a user can always provide their own overriding user snippets for the other mode.

Ultimately I'd like to see the snippets converted to completions for multiple reasons:
1.  Markdown descriptions can be used for better help (e.g. links)
2. This behavior could be configurable or could auto-detect wordseparators

**Comment by JustinGrote** [comment]
Also I personally am team "$ is not a word separator" mostly because it makes double-click + ctrl-f2 to rename all symbols more error prone, unless we come up with a way to do a proper rename symbol in Powershell

**Comment by andschwa** [comment]
> Should DSC move to community snippets?

Eh, sure, if we have that setup.

> Should we still have examples or should the examples be with placeholders?

I'm down to remove them. They could be in a help file if we wanted.

> Should Pester Move to Community Snippets since it is no longer bundled with Powershell?

You'd be the expert on this! Perhaps they should? But also everyone uses Pester with PowerShell, it's the default test framework really.

> Intellisense now handles the requires, there was a comment that these should be removed when it does.

Sweet!

> Workflows are deprecated and not supported in 6+, we should not be encouraging their use.

Sounds good to me!

> NEW

Loving it!

P.S. Sorry this took me a while to get to! Testing them out right now.

**Review by andschwa — APPROVED** [review]

**Comment by andschwa** [comment]
Thanks so much @JustinGrote!

**Pull request merged**
