### PR TITLE
Add WhitespaceBetweenParameters option for PSSA 1.19

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

Turned off by default to reduce potential impact if people don't like it or should there be bugs. PR ready but pending PSSA release.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [ ] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Given the timing of PS7, vscode extension, and PSSA releases - can you move this change into your other PR so we prevent a merge conflict?

**Comment by bergmeister** [comment]
Ok, so just 1 PR for all new PSSA settings in 1.19?

**Comment by TylerLeonhardt** [comment]
Yes please!

**Comment by bergmeister** [comment]
Closing in favour of #2674

**Pull request closed without merging**
