### PR TITLE
Patch 1

### LINKED ISSUE #864: Improve visibility of hyphen/dash in the PowerShell ISE theme when typing in the editor
_From @stefanstranger on June 12, 2017 13:26_

Please change the setting for the ISE Theme so you can see the dash when interactively typing to:
```
"colors": {
		"activityBar.background": "#E1ECF9",
		"activityBar.foreground": "#A9A9A9",
		"activityBarBadge.background": "#A9A9A9",
		"editor.lineHighlightBackground": "#add8e6",
		"editor.selectionBackground": "#94c6f7",
		"statusBar.background": "#999999",
		"statusBar.debuggingBackground": "#FF4500",
		"statusBar.noFolderBackground": "#999999",
		"terminal.background": "#012456",
		"terminal.foreground": "#F5F5F5"
	}
```

Changed editor.lineHighlightBackground setting from **#94c6f7** to **#add8e6**

/Stefan

_Copied from original issue: PowerShell/PowerShellEditorServices#511_

### PR DESCRIPTION
**Pull request by stefanstranger**
Solves issue with not seeing dashes when editor line is selected. 

Fixes #864.

### CODE REVIEW

**Comment by daviwil** [comment]
You shouldn't have to sign a CLA for a one-line change, I think the automation bot is getting confused by all the other commits.  Can you check the "Allow edits from maintainers" box here:

image

Once that's checked I can fix it for you.

**Comment by rkeithhill** [comment]
I wonder if this should be rebased against `upstream/master`?

**Comment by daviwil** [comment]
Yeah, that's the fix, I just didn't want him to have to learn how to rebase for his first PR ;)

**Comment by rkeithhill** [comment]
The PR is trying to merge into `develop`.  Thought we were going to drop `develop` and just use `master`?

**Comment by daviwil** [comment]
Nice catch!  That was the issue.

**Comment by daviwil** [comment]
I'm going to close/reopen to see if it gets CLA bot to not require CLA.

**Comment by rkeithhill** [comment]
It's only taken about a year and a half but I'm finally starting to grok Git with much help/coaching from you - so thanks!

**Comment by daviwil** [comment]
Haha, you give me too much credit.

Thanks for the PR Stefan, merging it!

**Comment by mattmcnabb** [comment]
Was this just an update to the editor highlight color? I'm not certain what dashes were not visible - @stefanstranger  do you have a screenshot?

**Pull request merged**
