### PR TITLE
{DO NOT MERGE} (GH-1609) Remove syntax folder provider feature

### LINKED ISSUE #1609: Move syntax aware folding provider to PowerShell Editor Services
**Summary of the new feature**

The syntax aware folding provider should really be in PowerShell Editor Services.  This feature requests track the work to remove the provider in the extensions.

The issue to add the folder to the editor services is at;
https://github.com/PowerShell/PowerShellEditorServices/issues/793

### PR DESCRIPTION
**Pull request by glennsarti**
**THIS PR SHOULD NOT BE MERGED UNTIL https://github.com/PowerShell/PowerShellEditorServices/pull/777 is merged**

## PR Summary

Now that the PowerShell Editor Services has a Folding Provider, this extension
based feature is no longer required.  This commit removes the feature and tests.

The PSES Issue #793 [1] tracks the work to add it to PSES.

[1] https://github.com/PowerShell/PowerShellEditorServices/issues/793

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] PR has tests
- [ ] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

Fixes #1609

### CODE REVIEW

**Comment by rjmholt** [comment]
We should link to the relevant VSCode feature documentation in the issue

**Comment by glennsarti** [comment]
I haven't seen the source code but this what I've observed;

1. If the language server says it provides a Folding Provider VSCode uses that.
2. If the extension registers a FoldingProvider the VSCode uses that.
3. Otherwise it defaults to the indentation default folder within VSCode

**Comment by rjmholt** [comment]
Oh right, so the registration is in the `FoldingProvider.Enable` (or whatever it is) part of the initialisation message response?

**Comment by glennsarti** [comment]
> We should link to the relevant VSCode feature documentation in the issue

AFAIK There is no explicit documentation on this

**Comment by glennsarti** [comment]
> Oh right, so the registration is in the FoldingProvider.Enable (or whatever it is) part of the initialisation message response?

Yes. The logic in PSES is;

1. The Server says it supports folding and the folder is enabled.
2. The client later sends the ConfigNotification which then enables or disables the folder in PSES

**Comment by rjmholt** [comment]
> AFAIK There is no explicit documentation on this

Bugger. I'll keep search just so we have a few signposts on how it all works.

**Comment by glennsarti** [comment]
The deep internal reference documentation of VSCode isn't the greatest :-(

**Comment by glennsarti** [comment]
Works on my machine.  Would appreciate someone on Mac and/or Ubuntu to try it out.

**Comment by TylerLeonhardt** [comment]
Checked out your code in both repos. Can confirm, works on macOS 😄

Folding a here string worked perfectly and settings updates were automatically applied.

**Comment by cpdohert** [comment]
The new syntax folding doesn't work correctly.  Prior to this PR, "Fold All" did what I expect: function definitions collapsed into a single line, etc.  Now, folding is randomly collapsing more than a single function/stanza, or not an entire function/stanza.  Syntax folding is essentially completely broken for our PowerShell module authoring as of this PR.  I can't easily provide examples witout violating company NDA, but if I am not the only one with this issue I can generate representative code that displays the problem.

**Pull request merged**
