### PR TITLE
Add new Pester 5 GA Output Types

### PR DESCRIPTION
**Pull request by JustinGrote**
New Pester 5 Output Types were added last-minute to GA. These should also be available in the extension pester settings options.
https://github.com/pester/Pester/blob/v5.0/README.md#actual-breaking-changes

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] PR has tests
- [ ] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by JustinGrote** [comment]
@TylerLeonhardt FYI the build appears to be failing for external reason to this change.

**Comment by TylerLeonhardt** [comment]
Yep I'm working on that

**Comment by TylerLeonhardt** [comment]
cc @nohwnd for visibility.

**Comment by TylerLeonhardt** [comment]
@JustinGrote we should probably add the appropriate values to this switch:

https://github.com/PowerShell/vscode-powershell/blob/master/InvokePesterStub.ps1#L80-L84

**Comment by nohwnd** [comment]
@JustinGrote @TylerLeonhardt  that switch is okay, the default output for v4 should be All, which it is. 

The command help does not mention all the options, so imho this is good to go :)

**Comment by TylerLeonhardt** [comment]
Thanks @JustinGrote!

**Pull request merged**
