### PR TITLE
Change changelog script to use PSES syntax

### PR DESCRIPTION
**Pull request by rjmholt**
## PR Summary

Changes the changelog generation script so the output doesn't need rewriting on releases.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by tylerl0706** [comment]
Can you post the output for reference?

**Comment by rjmholt** [comment]
Example:

```
> .\tools\Get-PowerShellExtensionChangelog.ps1 -LastReleaseTag 'v1.8.2' -NewReleaseTag 'v1.8.3' -Token <my-token>

## v1.8.3
### Thursday, August 16, 2018
#### [vscode-powershell](https://github.com/powershell/vscode-powershell)

- Update CHANGELOG for v1.8.3 (#1483)
- Use PowerShell signing script in VSTS builds (#1480)
- Use newer version for preleases (#1460)
- Change resourceLangId to editorLangId so right-click works properly with unsaved files (#1475) (Thanks @corbob!)
- (GH-1458) Remove region folding from non-region areas (#1467) (Thanks @glennsarti!)

#### [PowerShellEditorServices](https://github.com/powershell/PowerShellEditorServices)

- Increment version number
- Update CHANGELOG for v1.8.3 (#723)
- Add VSTS signing step (#722)
- increment version for prerelease (#717)
- Reduce allocations when parsing files (#715) (Thanks @mattpwhite!)
```

**Comment by rjmholt** [comment]
Example:

```
> .\tools\Get-PowerShellExtensionChangelog.ps1 -LastReleaseTag 'v1.8.2' -NewReleaseTag 'v1.8.3' -Token $myToken

## v1.8.3
### Thursday, August 16, 2018
#### [vscode-powershell](https://github.com/powershell/vscode-powershell)

- [vscode-PowerShell](https://github.com/PowerShell/vscode-PowerShell) -
  Change changelog script to use PSES syntax
- [vscode-PowerShell #1483](https://github.com/PowerShell/vscode-PowerShell/pulls/1483) -
  Update CHANGELOG for v1.8.3
- [vscode-PowerShell #1480](https://github.com/PowerShell/vscode-PowerShell/pulls/1480) -
  Use PowerShell signing script in VSTS builds
- [vscode-PowerShell #1460](https://github.com/PowerShell/vscode-PowerShell/pulls/1460) -
  Use newer version for preleases
- [vscode-PowerShell #1475](https://github.com/PowerShell/vscode-PowerShell/pulls/1475) -
  Change resourceLangId to editorLangId so right-click works properly with unsaved files  (Thanks @corbob!)
- [vscode-PowerShell #1467](https://github.com/PowerShell/vscode-PowerShell/pulls/1467) -
  (GH-1458) Remove region folding from non-region areas  (Thanks @glennsarti!)

#### [PowerShellEditorServices](https://github.com/powershell/PowerShellEditorServices)

- [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices) -
  Increment version number
- [PowerShellEditorServices #723](https://github.com/PowerShell/PowerShellEditorServices/pulls/723) -
  Update CHANGELOG for v1.8.3
- [PowerShellEditorServices #722](https://github.com/PowerShell/PowerShellEditorServices/pulls/722) -
  Add VSTS signing step
- [PowerShellEditorServices #717](https://github.com/PowerShell/PowerShellEditorServices/pulls/717) -
  increment version for prerelease
- [PowerShellEditorServices #715](https://github.com/PowerShell/PowerShellEditorServices/pulls/715) -
  Reduce allocations when parsing files  (Thanks @mattpwhite!)

```

**Comment by tylerl0706** [comment]
sweeeeeeeeet

**Comment by dragonwolf83** [comment]
Can we exclude versioning increment and update changelog messages? They are internal processes that adds noise and is not needed in a Change Log.

**Pull request merged**
