### PR TITLE
{WIP} (GH-1514) Show last line folding

### PR DESCRIPTION
**Pull request by glennsarti**
## PR Summary

Alternative implementation of #1514

## PR Checklist

DO NOT MERGE

### CODE REVIEW

**Comment by glennsarti** [comment]
Example alternate PR for #1546

**Comment by glennsarti** [comment]
@rjmholt I wasn't keen on adding a devDependency for a Mocha mocking framework so I used a class wrapper for the folding provider instead.

**Comment by glennsarti** [comment]
Closing in preference to #1557

**Comment by rjmholt** [comment]
@glennsarti I think new dependencies to reduce friction on testing seems pretty justified. We can discuss with @tylerl0706 and @rkeithhill.

**Pull request closed without merging**
