### PR TITLE
New-EditorFile works on non-powershell untitled files

### LINKED ISSUE #810: $pseditor.GetEditorContext().CurrentFile.GetTextLines() throws on Untitled (never saved) file
### System Details

```
Windows 10 CU
VSCode 1.12.2
Extension 1.2.0
PS 5.1.15063.296
```

### Issue Description

This is the error I get in the PSIC:
```
PowerShell Integrated Console

~\Documents\WindowsPowerShell
1:74ms>

A terminating error occurred in PowerShell Editor Services:

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.WaitForExit()
   at CallSite.Target(Closure , CallSite , Object )
One or more errors occurred.

Could not find file 'C:\Users\hillr\Documents\WindowsPowerShell\Untitled-1'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
 FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientCont
ext)
   at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest command
Details, RequestContext`1 requestContext)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass3_0`4.<SetRequestHandler>b__0(Message reques
tMessage, MessageWriter messageWriter)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
   at System.Threading.Tasks.Task.Execute()
```

It might actually be failing on accessing `CurrentFile`. 

Here are the contents of my Microsoft.VSCode_profile.ps1 file:
```posh
# Lame semicolon remover - doesn't understand here strings or comments
function Remove-TrailingSemicolon {
    param(
        [Parameter()]
        [Microsoft.PowerShell.EditorServices.Extensions.EditorContext]
        $editorContext = $psEditor.GetEditorContext()
    )

    $currentFile = $editorContext.CurrentFile;
    $lines = $currentFile.GetTextLines();
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -match '^(.*?);(\s*)$') {
            $startCol = $matches[1].Length + 1
            $currentFile.InsertText(' ', $i+1, $startCol, $i+1, $startCol+1)
        }
    }
}

$params = @{
    Name = 'KH.RemoveUnnecessarySemicolons'
    DisplayName = 'Remove unnecessary semicolons'
    Function = 'Remove-TrailingSemicolon'
    SuppressOutput = $true
}

Register-EditorCommand @params
```

### Attached Logs
```
5/31/2017 4:35:21 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 17,
      "method": "powerShell/invokeExtensionCommand",
      "params": {
        "name": "KH.RemoveUnnecessarySemicolons",
        "context": {
          "currentFilePath": "Untitled-1",
          "cursorPosition": {
            "line": 9,
            "character": 0
          },
          "selectionRange": {
            "start": {
              "line": 9,
              "character": 0
            },
            "end": {
              "line": 9,
              "character": 0
            }
          }
        }
      }
    }

5/31/2017 4:35:21 PM [VERBOSE] - Method "ResolveFilePath" at line 316 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Workspace\Workspace.cs

    Resolved path: C:\Users\hillr\Documents\WindowsPowerShell\Untitled-1

5/31/2017 4:35:21 PM [ERROR] - Method "OnListenTaskCompleted" at line 494 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\hillr\Documents\WindowsPowerShell\Untitled-1'.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass3_0`4.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__47.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'C:\Users\hillr\Documents\WindowsPowerShell\Untitled-1'.
    File name: 'C:\Users\hillr\Documents\WindowsPowerShell\Untitled-1'
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
       at Microsoft.PowerShell.EditorServices.Workspace.GetFile(String filePath)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServerEditorOperations.ConvertClientEditorContext(ClientEditorContext clientContext)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleInvokeExtensionCommandRequest(InvokeExtensionCommandRequest commandDetails, RequestContext`1 requestContext)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<>c__DisplayClass3_0`4.<SetRequestHandler>b__0(Message requestMessage, MessageWriter messageWriter)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.MessageDispatcher.<DispatchMessage>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<ListenForMessages>d__47.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.PowerShell.EditorServices.Utility.AsyncContext.Start(Func`1 asyncMainFunc)
       at System.Threading.Tasks.Task.Execute()<---
```

### PR DESCRIPTION
**Pull request by tylerl0706**
Partnered with: https://github.com/PowerShell/PowerShellEditorServices/pull/774

This fixes the problem where `$psEditor.GetEditorContext()` assumed that the file open was a real file on the file system OR a powershell untitled file. Since that isn't always the case, It would throw an exception:

```
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred. (Could not find file '/Users/tyler/Code/PowerShell/vscode/PowerShellEditorServices/untitled:Untitled-1'.)"
At /Users/tyler/.vscode-insiders/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1:152 char:13
+             $psEditor.GetEditorContext().CurrentFile.InsertText(($val ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : AggregateException
```

This also means that `New-EditorFile -Value 'asdf'` actually works when you don't have your default language mode set to PowerShell.

This PR was needed to give GetEditorContext the content of the untitled file. 

fixes #810

### CODE REVIEW

**Comment by tylerl0706** [comment]
Yeah that was from a rebase I think

**Comment by SeeminglyScience** [comment]
@tylerl0706 my understanding is that if you rebase a branch that is already published you need to force push for it to be clean.  That does rewrite history, but it's probably fine for a fork.  You can also do a merge instead which will group it probably.

That said I'm not a git ninja so ymmv 😉

**Comment by tylerl0706** [comment]
Yeah looking at the history (because I forgot lol), that's what I did (a rebase) which is what I wanted.

Had to force push to rewrite history but I wanted that because I wanted my commits in this PR to be after what's in master.

I think it's typically a good idea to rebase before merging - especially when the target branch had a lot of action - just to make sure your stuff works with what's currently in the target.

A merge from target to incoming works fine too... But I like the idea of my PR commits being after what's in the target

**Comment by SeeminglyScience** [comment]
@tylerl0706 are you sure you force pushed though? That looks like a normal push after rebase (the button in VSCode is a normal push)

**Comment by tylerl0706** [comment]
Yeah I'm pretty sure I did. I typically use the git CLI. I'll double check though

**Comment by tylerl0706** [comment]
Yep the log looks good and I even did a force push again and that said everything is up to date.

```
10-24 10:01:18 ~/Code/PowerShell/vscode/vscode-powershell [fix-new-editorfile]
→ git log
commit 0435f8f6ee485d0424e6de90eb955a25b01997e6 (HEAD -> fix-new-editorfile, personal/fix-new-editorfile)
Merge: c4db8d7 6d46bdc
Author: Tyler Leonhardt <tylerl0706@gmail.com>
Date:   Sun Oct 21 08:48:25 2018 +0800

    merge conflict

commit c4db8d7c78c994cfbb78b77142ec059145c08617
Author: Tyler Leonhardt <tylerl0706@gmail.com>
Date:   Sun Oct 21 08:46:46 2018 +0800

    add currentFileLanguage

commit c386369b18058c2fcfe75c6fb11573f05f1447df
Author: Tyler Leonhardt <tylerl0706@gmail.com>
Date:   Sun Oct 14 08:18:29 2018 +0700

    New-EditorFile works on non-powershell untitled files

commit 0388343e13e4baadfffc34b25d6d49a6200fee58 (origin/master, origin/HEAD, master)
Author: Robert Holt <rjmholt@gmail.com>
Date:   Mon Oct 15 18:44:00 2018 -0700

    [Ignore] Update PSScriptAnalyzer issue template (#1585)

    Make the PSScriptAnalyzer issue redirect template more explicit about what PSScriptAnalyzer handles in the PowerShell extension.

commit 55e8ca33cae05bc0ac8dc37818094d3dded692e4
Author: corbob <30301021+corbob@users.noreply.github.com>
Date:   Mon Oct 15 14:13:32 2018 -0700

    Log when languageClient not loaded during initialization (#1555)

    * Log when languageClient not loaded.
    Copy the pattern from ExtensionsCommandsFeature to the other instances of the check without a log of the error.

commit 6d46bdc813a2bbca704659b175e63375fc4cdac6
Author: Tyler Leonhardt <tylerl0706@gmail.com>
Date:   Sun Oct 14 08:18:29 2018 +0700
```
```
10-24 10:01:38 ~/Code/PowerShell/vscode/vscode-powershell [fix-new-editorfile]
→ git status
On branch fix-new-editorfile
nothing to commit, working tree clean
```
```
10-24 10:01:40 ~/Code/PowerShell/vscode/vscode-powershell [fix-new-editorfile]
→ git push personal fix-new-editorfile -f
Everything up-to-date
```

**Pull request merged**
