### PR TITLE
Add optional UI to prompt for script args.

### PR DESCRIPTION
**Pull request by rkeithhill**
Address one issue #705

### CODE REVIEW

**Comment by rkeithhill** [comment]
This is not quite ready yet.  I'm waiting on some resolution to this issue - https://github.com/Microsoft/vscode/issues/25712

**Comment by daviwil** [comment]
Awesome!  I suppose we'll wait for the next VS Code update before shipping this in the PS extension?

**Comment by rkeithhill** [comment]
Yes.  I keep testing daily builds of VSCode Insiders but haven't observed the fixed behavior yet.

**Comment by rkeithhill** [comment]
OK, the issue is fixed in today's insiders build.  It should ship in the (late) May release.

**Comment by rkeithhill** [comment]
One more thing to do. Need to figure out a debug config snippet for this.  I'll propose one here in a bit.

**Comment by rkeithhill** [comment]
Here is what the Debug configuration list looks like now (from the Examples folder):
image

This is what the Add Configuration choices look like:
image

**Comment by rkeithhill** [comment]
> I suppose we'll wait for the next VS Code update before shipping this in the PS extension?

We can ship this before the May VSCode release drops.  I added code to check the VSCode version and I only enable the "save the prev args" features if we're on 1.13 or later.

**Comment by rkeithhill** [comment]
I'm not sure I like the args being saved across separate VSCode sessions.  Let me see if I can find a way to store the args just for the current session.

**Comment by daviwil** [comment]
Using "PS" as the prefix just feels wrong to me even though I can understand your reason for doing it.  As far as I know, nobody has complained about not being able to see the name in the debug UI.  Maybe we should leave it the way it is so that it's clearer?

I suppose there's also the possibility of rewording them slightly.  Instead of "PowerShell Launch Current File" it could be "Launch Current PowerShell File", "Interactive PowerShell Session" instead of "PowerShell Interactive Session", etc.  What do you think?

**Comment by rkeithhill** [comment]
OK putting PS back to PowerShell.  I think it is better to leave PowerShell first because so that in the mixed debug configuration scenario, the PowerShell configs sort next to one another.  PR coming.

**Comment by daviwil** [comment]
Thanks Keith!  This change is pretty awesome, I like the new feature a lot.  Is it ready to be merged now?

**Comment by rkeithhill** [comment]
I think so.  Do you think it is OK to remember scripts args between sessions using workspaceState?

**Comment by daviwil** [comment]
Yeah, I think that's a great way to do it.  We might need a way to clear the stored args in the future, but I wouldn't worry about it until someone asks for it.  Merging it now, thanks man!

**Comment by rkeithhill** [comment]
I think this will make for a nice little debugging enhancement.

**Pull request merged**
