### PR TITLE
Auto-complete comment help for functions

### PR DESCRIPTION
**Pull request by kapilmb**
Related PRs
* PowerShell/PowerShellEditorServices#452
* PowerShell/PSScriptAnalyzer#761

### CODE REVIEW

**Comment by kapilmb** [comment]
Here is quick demo of the feature - 

auto-help-completion

**Comment by daviwil** [comment]
That is incredibly cool!  Does the `##` form of help work for PowerShell's help system?

**Comment by daviwil** [comment]
It'd be nice if we could remove the selection of the text after it gets inserted.  Even better if the cursor could be placed inside of the synopsis field (though I know it's probably not super easy).  In the future it'd be nice to do this as a dynamic snippet so that you can tab through the fields to enter the new text.

**Comment by rkeithhill** [comment]
> In the future it'd be nice to do this as a dynamic snippet

That would be cool and could replace the current `comment-help` snippet.

**Comment by kapilmb** [comment]
Yes, `##` works with PS help system.

I think removing the selection and putting the cursor in the synopsis field shouldn't be hard as we know the location of the synopsis relative to the trigger characters. But, I think tabbing through the fields without going through the snippet completion provider might be difficult. I am not sure if snippet provider has a default completion mode i.e. the user doesn't have to tab through the completion candidates, the editor just inserts the best match (a la `I am feeling luck`). If it has such a feature then we can perhaps remove a lot of the custom logic from the client side.

**Comment by daviwil** [comment]
You can provide default values for the snippet fields:

> A snippet can define tab stops and placeholders with $1, $2 and ${3:foo}. $0 defines the final tab stop, it defaults to the end of the snippet. Variables are defined with $name and ${name:default value}. The full snippet syntax is documented here.

The user can confirm the defaults by hitting ESC I think.  It looks like you can insert a snippet into the document without a completion provider, check out the `TextEditor.insertSnippet` method:

```
insertSnippet(snippet: SnippetString, location?: Position | Range | Position[] | Range[], options?: {undoStopAfter: boolean, undoStopBefore: boolean}): Thenable<boolean>
```

Might be doable!  Only real challenge is inserting the snippet syntax into PSScriptAnalyzer's correction without it making the code nasty.

**Comment by kapilmb** [comment]
wow! stay tuned for the snippet version then! 😃

**Comment by daviwil** [comment]
Awesome!  I think that'd make it pretty much perfect :)

**Comment by rkeithhill** [comment]
We will probably want to remove the current `comment-help` snippet.  Also, some folks use `<#` for generic multiline comments or to comment out sections of code.  Just want to make sure we don't get comment help in these scenarios.

**Comment by daviwil** [comment]
I think this functionality only appears if you type `<#` at the top of a function definition, or at least that should be the case.

**Comment by rkeithhill** [comment]
But what if my intent is to comment out the function?  :-)  In general, you can avoid snippet completion by pressing <kbd>Esc</kbd> or clicking away.

**Comment by daviwil** [comment]
In this case you'll get some really nice comment-based help to go with your commented-out function ;)  We'll polish it up after the first iteration.

**Comment by kapilmb** [comment]
How about this -

auto-help-completion-tab-stops

**Comment by daviwil** [comment]
Perfect!  Does it work to cancel out of the property fields when you hit ESC?

**Comment by kapilmb** [comment]
We will definitely polish the experience, but here is another workaround for the case when if someone just wants use `<#` without the comment help, they can just undo the completion (ctrl-z or whatever key they have assigned to undo) which will give you the original `<#` without any help.

**Comment by kapilmb** [comment]
By *cancel out the property fields* do you mean that the tabbing loses focus?

**Comment by rkeithhill** [comment]
Looking good. My only qualm is the `######` form of comments. In years since we've had comment-based help, I can't say I've ever seen that form of help commenting.   Do you we want to promote that style?

**Comment by kapilmb** [comment]
I think we should leave it up to the user to choose between `BlockComment` or `LineComment` style. But maybe by default we should set the comment style to `BlockComment` ?

**Comment by rkeithhill** [comment]
If we allow `LineComment`, someone's going to ask to configure the length of the first and last `#############` lines.  :-)

**Comment by daviwil** [comment]
I also don't see the `####` style very often (or ever, to be honest) so I'm not sure how many people would even try it.  Maybe it's worth only completing the `<#` style in VS Code at first when the user is typing and then wait to see if anyone asks for the other form.  If they do, we could easily turn it on.

As far as the PSScriptAnalyzer rule is concerned, I'm fine with the user having an option there so that part of the code could definitely stay in.

**Comment by kapilmb** [comment]
> If we allow LineComment, someone's going to ask to configure the length of the first and last `#############` lines. :-)

Good point. May be we just remove the `######` at the beginning and the end - It will still leave the comment help valid and we don't have deal with issue of its length. I have seen people use the line comment style but as both of you have mentioned, it is rare. I will just leave the option there in PSSA, since it is already there, but it doesn't have to be present in the extension.

**Comment by rkeithhill** [comment]
> I will just leave the option there in PSSA, since it is already there, but it doesn't have to be present in the extension.

Sounds good to me.

**Comment by andysimmons** [comment]
Love it! This is awesome.

**Comment by brsh** [comment]
How about if the snippet could work INSIDE the function? (a la https://technet.microsoft.com/en-us/library/hh500719.aspx: 'It’s preferable to include the help within the function rather than just before. That helps keep the comment "part" of the function, and ensures Windows PowerShell won’t confuse it for something else.').

Plus, I like it better :)

**Comment by rkeithhill** [comment]
@brsh Not everybody agrees with that placement (I sure don't).  :-)  That said, seems like it could be made to work in both locations.

**Comment by daviwil** [comment]
We're going to make it work both ways.  PSScriptAnalyzer's rule which provides this behavior is capable of placing it both outside and inside of the function definition, we just need to expose it as an option in the extension.  I've just filed issue #763 to track this for the next feature update.

**Comment by stefanstranger** [comment]
I agree with @brsh I also like to have my help within the function so when I collapse functions the help is also collapsed within the function. The Function Snippet in the ISE with help outside the function bothered me so much I created new Snippets to solve this ;-) 
But it is for sure a personal thing :-)

**Comment by daviwil** [comment]
@rbobot you mean above CmdletBinding in a function definition or somewhere else? If in a function, #763 is tracking that.

**Comment by brsh** [comment]
Woohoo! Thanks! I'm all for personal opinions (and for sometimes changing them: I'm coming around on spaces vs tabs), but it's great to have tools that can support them (and people who support those tools). This extension is what moved me over to vscode. It just keeps getting better, and I'm grateful!

**Comment by BCAdler** [comment]
The only issue with this is that to compress multi-line comments there has to be a space on each line of the multi-line comment.  More of a bug with the extension I'd say though.

**Comment by jkavanagh58** [comment]
@rbobot Are you referring to having this comment based auto-complete help for a script, not just limited to functions? That is my question anyway.

**Comment by jkavanagh58** [comment]
@rbobot agreed!

**Comment by daviwil** [comment]
Hey guys, here's the issue tracking that feature request: https://github.com/PowerShell/vscode-powershell/issues/769

**Pull request merged**
