### PR TITLE
Remove broken 'Select PSScriptAnalyzer Rules' command

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

Related (but not fixing the issue itself): #2422

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@bergmeister can you also delete this file and all references?

https://www.github.com/PowerShell/vscode-powershell/tree/master/src%2Ffeatures%2FSelectPSSARules.ts

(It'd be good to do a quick scan of the repo for other references)

The reason I ask is cause I think once PSSA vNext is out, we can totally redesign this feature and if we need to reference it in the future, we have it in the git history.

**Comment by bergmeister** [comment]
@TylerLeonhardt Good point. Will do.

Just FYI this came up again in the PowerShell `#vscode` Slack channel by @wsmelton who wanted to use that feature but found it was broken. His words were:
> Pretty sad because I used it heavily for one off projects that are not on GitHub

I know the feature was polarizing before anyway due to it's lack of persistence but what was the reason for abandoning it completely? As far as I see it broke because the GetPSSARulesRequest\GetPSSARulesRequest classes in PSES were removed. Would it be easy to re-add them or would it be much more difficult due to re-architecture?

**Comment by TylerLeonhardt** [comment]
> what was the reason for abandoning it completely?

Like I said in #2422 ...

My reasoning was:

* It felt like an incomplete feature - it's only active during your current session which is a silly limitation and should be backed by a PSScriptAnalyzer settings file somewhere
* I doubted it was being used...

I still doubt that many users actually use it and it even promotes a less than ideal practice:
> set this every time you start VS Code rather than using a PSScriptAnalyzerSettings file

 I want to bring back the feature because the UX is not terrible (selecting the rules you care about) but considering PSSA v2 is going to change the rules a bunch, it just doesn't seem like it's worth the time at the moment.

If you want to bring it back, I won't say no to it, but I don't have the bandwidth, unfortunately.

**Comment by bergmeister** [comment]
OK, I've removed the code for now, which will at least resolve the user confusion of people who try to use the command. I might try to see if it is easy to re-add at a later point in time, so maybe one step at a time.

**Pull request merged**
