### PR TITLE
[Ignore] Stop building the v2 branch in master

### PR DESCRIPTION
**Pull request by rjmholt**
## PR Summary

The build for `master` is still downloading @SeeminglyScience's PSReadLine branch.

This gets rid of that, since that's now in the `2.0.0` branch.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

**Comment by tylerl0706** [comment]
How will this grab the PSES 2.0.0 branch?

**Comment by rjmholt** [comment]
AppVeyor [builds the `2.0.0` branch] -- `master` doesn't have a 2.0.0 build. Means the extension VSIX will have a different version, so they can be interchanged more easily in VSCode contexts.

**Comment by tylerl0706** [comment]
Ah. I see. The Appveyor.yml grabs the 2.0.0 build of PSES in the 2.0.0 branch. 👍

**Comment by rjmholt** [comment]
https://ci.appveyor.com/api/buildjobs/ma1a8og5h1d0g5cu/artifacts/PowerShell-insiders.vsix

**Pull request merged**
