### PR TITLE
Added a snippet to send eMails to PowerShell.json

### PR DESCRIPTION
**Pull request by fullenw1**
## PR Summary

Added a snippet PowerShell.json which can be used to send emails.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not work in progress

### CODE REVIEW

**Comment by fullenw1** [comment]
I have added a snippet to PowerShell.json which can be used to send emails.

**Comment by tylerl0706** [comment]
Thanks for this @fullenw1! I like this snippet. We try to only include general use snippets in the PowerShell.json and I'm not 100% sure this is general purpose enough to fit there...

However, we recently added a [community snippets doc](https://github.com/PowerShell/vscode-powershell/blob/master/docs/community_snippets.md) that is used for sharing snippets with more specific domains!

I think this snippet would be best in that doc.

If you or (@rkeithhill) disagree, I'm happy to discuss further 🙂

**Comment by fullenw1** [comment]
You are right. I was not aware of Community snippet doc's existence until now. Thanks!

**Comment by fullenw1** [comment]
Going to put the snippet into Community snippet doc.

**Pull request closed without merging**
